### PR TITLE
Connect to API via https

### PR DESCRIPTION
**Pull request by dwhenry**
Changed `Net::HTTP.new` to `Net::HTTP.start` to use 
inbuild https vertification and setup

Without this change the API attempts to connect via HTTP regards of API URLs protocol and returns: 
```Errno::ECONNRESET: Connection reset by peer``` 
when trying to send emails.

### CODE REVIEW

**Comment by quis** [comment]
Checkout out locally. Can confirm that:

- tests pass for this branch
- tests fail in the expected way if running the test from this branch against the code in master

Do you have this working locally and actually sending messages through the Notify API?

**Comment by quis** [comment]
@dwhenry And thanks for this! 😄

**Comment by dwhenry** [comment]
@quis yes I can successfully send emails (have not tried SMS) with these changes. 

The `get_notification` and `get_notifications` code is still broken but planning to fix that in a separate PR.

**Comment by quis** [comment]
Looks good to me. Thanks again for this.

**Pull request merged**
